#include "stdio.h"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int fibonacci(int n)
{
    if (n == 0)
    {
        return 1;
    }
    if (n == 1)
    {
        return 2;
    }
    return (fibonacci(n - 2) + fibonacci(n - 1));
}

int fibonacciByTheMax(int n)
{
    int i = -1;
    int result = 0;
    while (result < n)
    {
        i++;
        result = fibonacci(i);
    }
    return i - 1;
}

int main()
{
    // printf("%d\n", fibonacciByTheMax(4000000)); // result is 31

    int total = 0;

    for (int i = 0; i <= 31; i++)
    {
        int n = fibonacci(i);
        if (n % 2 == 0)
        {
            total += n;
        }
        printf("n = %d \t total = %d\n", n, total);
    }

    return 0;
}
